micronaut:
  application:
    name: metadata-service
  server:
    port: 8082

datasources:
  default:
    url: jdbc:h2:mem:metadata_db
    driverClassName: org.h2.Driver
    username: sa
    password: "prerit123"

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
